# Generated by Django 3.2.5 on 2021-08-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='activeexercise',
            name='last_overload_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activeexercise',
            name='overload_history',
            field=models.CharField(default='0;', max_length=512),
        ),
        migrations.RemoveField(
            model_name='activeexercise',
            name='training',
        ),
        migrations.AddField(
            model_name='activeexercise',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='tracker.training'),
            preserve_default=False,
        ),
    ]
