# Generated by Django 3.2.5 on 2021-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210801_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexercise',
            name='volume',
            field=models.CharField(default='0', max_length=128),
            preserve_default=False,
        ),
    ]
