# Generated by Django 3.2.5 on 2021-07-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210708_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverloadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_description', models.CharField(max_length=255)),
                ('type_identifier', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='training',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Exercise', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Plan', max_length=255),
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='Training', max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='plan',
            field=models.ManyToManyField(related_name='trainings', to='core.Plan'),
        ),
        migrations.CreateModel(
            name='ActiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overload_value', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('training', models.ManyToManyField(related_name='exercises', to='core.Training')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='overload_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.overloadtype'),
        ),
    ]
