# Generated by Django 3.2.5 on 2021-07-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeexercise',
            old_name='overload_value',
            new_name='last_overload_value',
        ),
        migrations.AddField(
            model_name='activeexercise',
            name='overload_history',
            field=models.CharField(default='0;', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='overload_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.overloadtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
